- name: Install and activate FTP
  hosts: all
  become: yes
  tasks:
  - name: install ftpd
    yum:
      name: vsftpd
      state: latest

  - name: activate ftpd
    service:
      name: vsftpd
      state: started
      enabled: yes

  - name: activate firewalld
    service:
      name: firewalld
      state: started
    
  - name: open ports
    firewalld:
      port: 21/tcp
      state: enabled
      permanent: true
    with_items:
  
  - name: open service
    firewalld:
      service: ftp
      state: enabled
      permanent: true

  - name: ftp reload
    service:
      name: firewalld
      state: restarted


